"""empty message

Revision ID: 4b15a37fd10b
Revises: b533c267ac70
Create Date: 2021-07-22 11:35:24.339035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b15a37fd10b'
down_revision = 'b533c267ac70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.String(length=2500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.drop_table('movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=2500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='movie_pkey'),
    sa.UniqueConstraint('title', name='movie_title_key')
    )
    op.drop_table('movies')
    # ### end Alembic commands ###
